version: '3.8'

services:
  thumbnail-generator:
    build:
      context: .
      dockerfile: Docker/api/dockerfile
    container_name: thumbnail-generator
    volumes:
      - ./api:/var/www/app
    working_dir: /var/www/app
    ports:
      - 1234:3456