version: '3.8'

services:
  thumbnail-generator:
    image: node:16.3-alpine3.13
    container_name: thumbnail-generator
    volumes:
      - ./api:/var/www/app
    working_dir: /var/www/app
    ports:
      - 1234:3456
    command: yarn run nodemon